# Generated by Django 5.0.7 on 2024-08-05 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='handle',
            field=models.CharField(blank=True, max_length=255, verbose_name='Handle of User'),
        ),
    ]
